// LIORA — fake catalog data
window.LIORA_KITS = [
  {
    id: "piel-grasa",
    name: "Kit Piel Grasa",
    eyebrow: "Cuidado personal · Piel",
    short: "Rutina de 30 días para equilibrar el sebo y reducir brillos sin resecar.",
    price: 89900,
    items: 5,
    category: "piel",
    photo: "sage",
    contains: [
      { name: "Limpiador suave matificante", size: "150 ml" },
      { name: "Tónico astringente sin alcohol", size: "120 ml" },
      { name: "Sérum niacinamida 5%", size: "30 ml" },
      { name: "Hidratante oil‑free", size: "50 ml" },
      { name: "Protector solar fluido FPS 50", size: "40 ml" },
    ],
    routine: [
      { time: "Mañana", step: "Limpia con agua tibia, aplica tónico, sérum y protector solar." },
      { time: "Noche", step: "Doble limpieza, tónico, sérum y una capa fina de hidratante." },
      { time: "Cada 5 días", step: "Sustituye el sérum por una mascarilla de arcilla 10 minutos." },
    ],
    note: "Si la irritación persiste más de 7 días, suspende el uso y consulta a tu médico.",
  },
  {
    id: "viaje",
    name: "Kit Viaje",
    eyebrow: "Esenciales · Tamaño cabina",
    short: "Siete esenciales en formato pequeño para mantener tu rutina lejos de casa.",
    price: 69900,
    items: 7,
    category: "viaje",
    photo: "warm",
    contains: [
      { name: "Limpiador 50 ml", size: "50 ml" },
      { name: "Hidratante 30 ml", size: "30 ml" },
      { name: "Protector solar 30 ml", size: "30 ml" },
      { name: "Bálsamo labial", size: "10 g" },
      { name: "Antiséptico de bolsillo", size: "30 ml" },
      { name: "Apósitos hidrocoloides", size: "10 u." },
      { name: "Necessaire de algodón", size: "—" },
    ],
    routine: [
      { time: "Antes de salir", step: "Llena los frascos con tu rutina habitual." },
      { time: "Mañana en el viaje", step: "Limpia, hidrata y aplica protector solar antes de salir." },
      { time: "Noche", step: "Limpieza simple si estás cansada — un solo paso es suficiente." },
    ],
    note: "Apto para equipaje de mano. Cumple la regla de líquidos de hasta 100 ml.",
  },
  {
    id: "gym",
    name: "Kit Gym",
    eyebrow: "Activo · Cuidado pre y post",
    short: "Para el cuerpo en movimiento — protección, recuperación y limpieza rápida.",
    price: 79900,
    items: 5,
    category: "activo",
    photo: "warm",
    contains: [
      { name: "Crema antifricción zonas activas", size: "75 ml" },
      { name: "Gel frío recuperador", size: "120 ml" },
      { name: "Spray refrescante para pies", size: "60 ml" },
      { name: "Toallitas limpiadoras x 20", size: "20 u." },
      { name: "Protector solar deportivo FPS 50+", size: "50 ml" },
    ],
    routine: [
      { time: "Antes", step: "Aplica antifricción en zonas de roce y protector solar si entrenas afuera." },
      { time: "Después", step: "Toallitas para limpiar, gel frío en músculos cargados, spray para pies." },
    ],
    note: "Evita aplicar gel frío sobre piel lastimada o con heridas abiertas.",
  },
  {
    id: "primeros-auxilios",
    name: "Kit Primeros Auxilios",
    eyebrow: "Hogar · Para tener a mano",
    short: "Lo esencial para resolver pequeños accidentes en casa con calma y método.",
    price: 99900,
    items: 12,
    category: "hogar",
    photo: "sage",
    contains: [
      { name: "Apósitos surtidos", size: "20 u." },
      { name: "Gasas estériles", size: "10 u." },
      { name: "Cinta micropore", size: "1 rollo" },
      { name: "Antiséptico líquido", size: "60 ml" },
      { name: "Crema cicatrizante", size: "30 g" },
      { name: "Pinzas + tijeras", size: "—" },
      { name: "Termómetro digital", size: "—" },
      { name: "Compresa fría/caliente", size: "—" },
      { name: "Suero fisiológico", size: "5 amp." },
      { name: "Guantes desechables", size: "5 pares" },
      { name: "Manual rápido LIORA", size: "—" },
      { name: "Estuche rígido", size: "—" },
    ],
    routine: [
      { time: "Cuando lo necesites", step: "Lava las manos, evalúa la situación y abre el manual rápido si dudas." },
      { time: "Cada 6 meses", step: "Revisa fechas de vencimiento y repón lo usado." },
    ],
    note: "No reemplaza atención médica. Llama a emergencias si hay sangrado abundante o pérdida de conciencia.",
  },
  {
    id: "bienestar",
    name: "Kit Bienestar",
    eyebrow: "Cuidado integral · Diario",
    short: "Suplementos y rutinas guiadas para sostener energía, sueño y digestión.",
    price: 119900,
    items: 6,
    category: "bienestar",
    photo: "dark",
    contains: [
      { name: "Magnesio bisglicinato", size: "60 cápsulas" },
      { name: "Vitamina D3 + K2", size: "60 cápsulas" },
      { name: "Probiótico diario", size: "30 sobres" },
      { name: "Té de hierbas para dormir", size: "20 bolsitas" },
      { name: "Diario de seguimiento", size: "1 unidad" },
      { name: "Guía de hábitos LIORA", size: "—" },
    ],
    routine: [
      { time: "Mañana", step: "Vitamina D3 con el desayuno y un sobre de probiótico en agua fría." },
      { time: "Noche", step: "Magnesio 30 minutos antes de dormir junto al té de hierbas." },
      { time: "Cada domingo", step: "Anota cómo te sentiste esta semana en el diario." },
    ],
    note: "Si tomas otros medicamentos, consulta a tu médico antes de iniciar suplementos.",
  },
];

window.LIORA_FILTERS = [
  { id: "todos", label: "Todos" },
  { id: "piel", label: "Piel" },
  { id: "bienestar", label: "Bienestar" },
  { id: "activo", label: "Activo" },
  { id: "viaje", label: "Viaje" },
  { id: "hogar", label: "Hogar" },
];

window.LIORA_PILLARS = [
  { icon: "guide", title: "Guía experta", sub: "en cada paso" },
  { icon: "routine", title: "Rutinas", sub: "personalizadas" },
  { icon: "info", title: "Información", sub: "clara y confiable" },
  { icon: "shield", title: "Uso seguro", sub: "y responsable" },
  { icon: "heart", title: "Acompañamiento", sub: "siempre" },
];

window.formatPrice = (n) => "$ " + n.toLocaleString("es-CO").replace(/,/g, ".");
